### ISSUE TITLE
下一頁連結錯誤

### ISSUE THREAD

**Issue by iendeavor** [ruizhengyun/typescript-note#3]
[Typescript 函数类型](https://github.com/ruizhengyun/typescript-note/blob/master/basic/function.md#you-can)

下一篇：Typescript 内置对象

連結多了`basic`

**Comment by ruizhengyun** [comment]
> [Typescript 函数类型](https://github.com/ruizhengyun/typescript-note/blob/master/basic/function.md#you-can)
> 
> 下一篇：Typescript 内置对象
> 
> 連結多了`basic`

感谢指出，本地 gitbook 复制过去，忘记改了。哈哈
